/*
 * File generated by Test generator (dotup.dotup-vscode-test-generator)
 * Date: 2021-02-22 06:32:48
 */
import { expect } from 'chai';
import * as net from 'net';
import { RtmpServer } from '../../../lib/rtmp/server';
import { BaseServer } from '../../../lib/base/server';
import { Logger } from '../../../lib/core/logger';
import { BaseSession } from '../../../lib/base/session';
import { RtmpSession } from '../../../lib/rtmp/session';
import { Utils } from '../../../lib/core/utils';

describe('Test class RtmpServer', () => {
  it('RtmpServer-run', () => {
    // Arguments

    // Method call
    const rtmpServer = new RtmpServer();
    rtmpServer.run();
  });

  it('RtmpServer-getSessions', () => {
    // Arguments

    // Method call
    const rtmpServer = new RtmpServer();
    const result = rtmpServer.getSessions();

    // Expect result
    expect(result).to.be.not.undefined;
  });
});
